### ISSUE TITLE
Some routes should work in both direction but do not

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/trRouting#299] opened 2024-09-09 15:08 UTC
In the od_mtl_2023 surveys, we got thousands of trips that should have matched but did not. Most are matching in one direction, but not the other.

Some example with GTFS for the Montreal region from autumn 2023
From/To école Laurentides from a home in Villeray:
<img width="811" alt="image" src="https://github.com/user-attachments/assets/630e4fec-d4b3-4461-8911-8d3617350871">
<img width="815" alt="image" src="https://github.com/user-attachments/assets/918dd0ac-9d71-4095-a274-b9f0d233b434">

Should match in both direction but only match in one:
De Castelnau > stm_2_ligne5Bleue > Snowdon
Snowdon > stm_2_ligne2Orange > Du Collège

**Comment by greenscientist** [comment] 2024-09-09 15:15
Donc environ le 7434 Drolet vers le 465 Rue Cardinal, Montréal, QC H4L 3C5

**Comment by greenscientist** [comment] 2024-10-03 17:57
Closing as we could not reproduce

**Closed as completed by greenscientist** 2024-10-03 17:57 UTC
Labels: bug
